# Generated by Django 2.1.1 on 2019-06-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=80, unique=True)),
                ('introduction', models.TextField(blank=True, db_column='INTRODUCTION', null=True)),
                ('director', models.CharField(blank=True, db_column='DIRECTOR', max_length=60, null=True)),
                ('actor', models.TextField(blank=True, db_column='ACTOR', null=True)),
                ('flag_time', models.CharField(blank=True, db_column='FLAG_TIME', max_length=4, null=True)),
                ('flag_area', models.CharField(blank=True, db_column='FLAG_AREA', max_length=8, null=True)),
                ('flag_type', models.CharField(blank=True, db_column='FLAG_TYPE', max_length=20, null=True)),
                ('score', models.FloatField(blank=True, db_column='SCORE', null=True)),
                ('url_img', models.TextField(blank=True, db_column='URL_IMG', null=True)),
                ('update_time', models.DateField(db_column='UPDATE_TIME')),
            ],
            options={
                'db_table': 'anime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=80, unique=True)),
                ('introduction', models.TextField(blank=True, db_column='INTRODUCTION', null=True)),
                ('director', models.CharField(blank=True, db_column='DIRECTOR', max_length=60, null=True)),
                ('actor', models.TextField(blank=True, db_column='ACTOR', null=True)),
                ('flag_time', models.CharField(blank=True, db_column='FLAG_TIME', max_length=4, null=True)),
                ('flag_area', models.CharField(blank=True, db_column='FLAG_AREA', max_length=8, null=True)),
                ('flag_type', models.CharField(blank=True, db_column='FLAG_TYPE', max_length=20, null=True)),
                ('score', models.FloatField(blank=True, db_column='SCORE', null=True)),
                ('url_img', models.TextField(blank=True, db_column='URL_IMG', null=True)),
                ('update_time', models.DateField(db_column='UPDATE_TIME')),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('vid', models.CharField(db_column='VID', max_length=8, primary_key=True, serialize=False)),
                ('rday', models.IntegerField(blank=True, db_column='RDAY', null=True)),
                ('rweek', models.IntegerField(blank=True, db_column='RWEEK', null=True)),
                ('rmonth', models.IntegerField(blank=True, db_column='RMONTH', null=True)),
            ],
            options={
                'db_table': 'ranking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tvseries',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=80, unique=True)),
                ('introduction', models.TextField(blank=True, db_column='INTRODUCTION', null=True)),
                ('director', models.CharField(blank=True, db_column='DIRECTOR', max_length=60, null=True)),
                ('actor', models.TextField(blank=True, db_column='ACTOR', null=True)),
                ('flag_time', models.CharField(blank=True, db_column='FLAG_TIME', max_length=4, null=True)),
                ('flag_area', models.CharField(blank=True, db_column='FLAG_AREA', max_length=8, null=True)),
                ('flag_type', models.CharField(blank=True, db_column='FLAG_TYPE', max_length=20, null=True)),
                ('score', models.FloatField(blank=True, db_column='SCORE', null=True)),
                ('url_img', models.TextField(blank=True, db_column='URL_IMG', null=True)),
                ('update_time', models.DateField(db_column='UPDATE_TIME')),
            ],
            options={
                'db_table': 'tvseries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UAnime',
            fields=[
                ('vid', models.IntegerField(db_column='VID', primary_key=True, serialize=False)),
                ('num', models.PositiveSmallIntegerField(db_column='NUM')),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
            ],
            options={
                'db_table': 'u_anime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UTvseries',
            fields=[
                ('vid', models.IntegerField(db_column='VID', primary_key=True, serialize=False)),
                ('num', models.PositiveSmallIntegerField(db_column='NUM')),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
            ],
            options={
                'db_table': 'u_tvseries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UVariety',
            fields=[
                ('vid', models.IntegerField(db_column='VID', primary_key=True, serialize=False)),
                ('num', models.PositiveSmallIntegerField(db_column='NUM')),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
            ],
            options={
                'db_table': 'u_variety',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=80, unique=True)),
                ('introduction', models.TextField(blank=True, db_column='INTRODUCTION', null=True)),
                ('director', models.CharField(blank=True, db_column='DIRECTOR', max_length=60, null=True)),
                ('actor', models.TextField(blank=True, db_column='ACTOR', null=True)),
                ('flag_time', models.CharField(blank=True, db_column='FLAG_TIME', max_length=4, null=True)),
                ('flag_area', models.CharField(blank=True, db_column='FLAG_AREA', max_length=8, null=True)),
                ('flag_type', models.CharField(blank=True, db_column='FLAG_TYPE', max_length=20, null=True)),
                ('score', models.FloatField(blank=True, db_column='SCORE', null=True)),
                ('url_img', models.TextField(blank=True, db_column='URL_IMG', null=True)),
                ('update_time', models.DateField(db_column='UPDATE_TIME')),
            ],
            options={
                'db_table': 'variety',
                'managed': False,
            },
        ),
    ]
